---
title: "Covid91 vaccine study Final2024"
author: "Davy D."
output:
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

$H_o$: There is no difference in drug effectiveness based on the following population subgroups; sex, drug use, sexual orientation.

$h_a$: There is a difference in drug effectiveness based on the following population subgroups; sex, drug use, sexual orientation.


## Methods

The variables of this study are Sex, Drug use, and sexual orientation.
We want to know if there is a difference of drug effectiveness based on the population subgroups, sex, drug use and sexual orientation which are all categorical variables, which means we are going to be using the Cat~Cat helper file. 


## Graphical Results

## Males

## Females

## LGBTQ

## Druggies

## Numerical Results

## Inferential Results

## Discussion and Conclussion
## Males


## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions